version: 0.0.0.{build}

shallow_clone: true

cache:
  - "%APPDATA%\\stack"
  - .stack-work

install:
  - choco install mingw --no-progress
  - refreshenv
  - choco install haskell-stack --no-progress
  - refreshenv

build_script:
  - "gcc --version"
  - "clang --version"
  - stack build kitlang:kitc
  - stack install
  - "7z a kit-{version}.7z .\std"
  - stack exec kitc -- -h
  - stack exec kitc -- --env
#  - TEST_RUNS=1 stack test --test-arguments '+RTS -N -RTS'

artifacts:
  - path: kit-{version}.7z
    name: kit-lang
