version: 0.0.0.{build}

shallow_clone: true

cache:
  - "%APPDATA%\\stack"
  - .stack-work

environment:
  matrix:
    - ARCH: x86
      CYGWIN: C:\Cygwin
      CHOST: i686-w64-mingw32
      CC: i686-w64-mingw32-gcc
    - ARCH: x86_64
      CYGWIN: C:\Cygwin64
      CHOST: x86_64-w64-mingw32
      CC: x86_64-w64-mingw32-gcc

install:
  - choco install haskell-stack --no-progress
  - choco upgrade haskell-stack --no-progress
  - refreshenv

build_script:
  - SET PATH=C:\%CYGWIN%\bin;%PATH%
  - "gcc --version"
  - "clang --version"
  - stack build kitlang:kitc
  - stack exec kitc -- -h
  - stack exec kitc -- --env
  - TEST_RUNS=1 stack test --test-arguments '+RTS -N -RTS'
  - stack install
